idf_component_register	(
SRCS 					"main.c"
						"../../esp32_common/tcp/ntp_sync.c"
						"../../esp32_common/utils/utils.c"
						"../../esp32_common/utils/ota.c"
						"../../esp32_common/cmds/cmd_wifi.c"
						"../../esp32_common/cmds/cmd_system.c"
						"../../esp32_common/tcp/mqtt_ctrl.c"
						"../../esp32_common/tcp/tcp_log.c"
#						"../../esp32_common/owb/onewire_bus_api.c"
#						"../../esp32_common/owb/onewire_bus_impl_rmt.c"
#						"../../esp32_common/owb/onewire_crc.c"
#						"../../esp32_common/owb/onewire_device.c"
#						"../../esp32_common/owb/ds18b20.c"
						"../../esp32_common/comm/i2ccomm.c"
						"../gate_op/gateop.c"
						"../westa_op/westaop.c"
						"../westa_op/dht22.c"
						"../westa_op/bosch_bmp280/bmp2.c"
						"../westa_op/aht20.c"
INCLUDE_DIRS 			"."
						"../certs"
						"../../esp32_common"
    					"../../esp32_common/cmds"
    					"../../esp32_common/tcp"
    					"../../esp32_common/utils"
    					"../../esp32_common/owb"
						"../gate_op"
						"../westa_op"
						"../westa_op/bosch_bmp280"
						"../../esp32_common/comm"
						)
